### ISSUE TITLE
csvOptions default params override

### ISSUE THREAD

**Issue by pakitovic** [Coderty/runnerty-executor-mysql#10]
Para sacar los headers de un csv actualmente hay que incluir siempre `headers: true` si se quiere cambiar algún otro parámetros como el separador:

```JS
        "csvOptions": {
          "headers": true,
          "delimiter": ";"
        }
```
Habría que unificar todos los parámetros (por defecto y los que se pasan) y solamente cuando se sobrescriba uno de los asignados por defecto sobrescribirlo

```JS
          const csvStream = csv
            .format(params.csvOptions || {
              headers: true
            })
```

**Comment by CarlosCarmona** [comment]
fixed in previous versions
