### ISSUE TITLE
extra_output.db_affectedRows not populated correctly

### ISSUE THREAD

**Issue by pakitovic** [Coderty/runnerty-executor-mysql#13]
Using mysql executor with updates, insert, etc that should fill up the executor's extraoutput area is not returning any data:

https://github.com/runnerty/executor-mysql/blob/69beb886367abe6153030ced73e127c6c1b7e77d/index.js#L193

It seems that hasOwnProperty is not evaluated to true:

```JS
            if (row.hasOwnProperty('ResultSetHeader')) {
              resultSetHeader = row.ResultSetHeader;
            }
```

Logging the variables displays that the row hasn't the ResultSetHeader property

```JS
            console.log('row');
            console.log(row);
            console.log('row.hasOwnProperty(\'ResultSetHeader\')');
            console.log(row.hasOwnProperty('ResultSetHeader'));
```

```
row
ResultSetHeader {
  fieldCount: 0,
  affectedRows: 27,
  insertId: 0,
  info: 'Rows matched: 27  Changed: 0  Warnings: 0',
  serverStatus: 34,
  warningStatus: 0,
  changedRows: 0
}
row.hasOwnProperty('ResultSetHeader')
false
```
OS: Mac OS Catalina
node: 14 LTS
runnerty: 2.8.0
mySQL executor: 2.1.3

**Comment by CarlosCarmona** [comment]
Thank you, this has been corrected in version 2.1.4.
